name: Build and release

on:
  push:
    # branches: [ master ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.3

    - name: Build
      run: ./build.sh

    - name: Build Docker image
      run: docker build --platform=linux/amd64 -t plotbot .

    - name: Push Docker image to Amazon ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-central-1
        local-image: plotbot
        image: plotbot

#    - name: Invoke deployment hook
#      uses: distributhor/workflow-webhook@v1
#      env:
#        webhook_url: ${{ secrets.WEBHOOK_URL }}
#        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
#        data: '{ "artifact_url": "${{ steps.upload_release_asset.outputs.browser_download_url }}", "secret": "${{ secrets.WEBHOOK_SECRET }}"  }'
       
